sonar.projectKey=eventweb
sonar.projectName=EventWeb Fullstack
sonar.projectVersion=1.0

# scan both frontend + backend
sonar.sources=backend/src,frontend/src

# ignore unnecessary folders
sonar.exclusions=**/node_modules/**,**/dist/**,**/.venv/**

# language (auto-detect works, but keep this)
sonar.sourceEncoding=UTF-8

# SonarQube server
sonar.host.url=http://localhost:9000
sonar.login=squ_15882220a3d51d4bc828c2df35d25f3a71f43ca8